### ISSUE TITLE
Request Fixes 

### ISSUE THREAD

**Issue by solomonshalom** [solomonshalom/Echo-Of-21k#4]
Hey! 

The images aren't showing up on the homepage as intended, please look at it. 
![image](https://user-images.githubusercontent.com/71135230/175319062-8bbeed1f-0e76-4db9-ac5a-97643075ae0a.png)

This issue needs to be solved immediately, this is urgent. 

With Warm Regards,
Solomon Shalom Lijo

**Comment by zaidajani** [comment]
Tomorrow

**Comment by zaidajani** [comment]
Sorry I'll do it day after tomorrow :)

**Comment by solomonshalom** [comment]
> Sorry I'll do it day after tomorrow :)

No Problem! @zaidajani

**Comment by zaidajani** [comment]
I'll surely do it today

**Comment by solomonshalom** [comment]
> I'll surely do it today

Oh, Great! I will be working on some UI fixes and website performance optimization by utilizing PartyTown and CDNs for the packages (Unpkg).

**Comment by solomonshalom** [comment]
So the issue has been fixed, turns out we just need to require it.
